export const metadata = {
  title: "Reshan - About",
  description: "Generated by create next app",
};


export default function About() {

  return (
    <div>
      <h1>About</h1>
    </div>
  )
}
