// import 'bootstrap/dist/css/bootstrap.min.css';
// import 'bootstrap/dist/js/bootstrap.bundle.min.js'; // Import Bootstrap JavaScript
// import 'bootstrap/dist/js/bootstrap.bundle.min.js'; // Import Bootstrap JavaScript
import "./globals.css";
import Footer from "@/components/Footer/Footer";
import Navbar from "@/components/Navbar/Navbar";
import { ThemeProvider } from "@/context/ThemeContext";

import { Montserrat } from "next/font/google";
const bodyFont = Montserrat({ subsets: ["latin"],
weight:['400','700', '900'] });

export const metadata = {
  title: "Reshan - HomePage",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={bodyFont.className}>
        <ThemeProvider>
            <div>
                <Navbar />
                {children}
                <Footer />
            </div>
        </ThemeProvider>
        </body>
    </html>
  );
}
